server:
  port: 9090
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: as
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    defer-datasource-initialization: true